---
title: "메타가소성 모델의 한계와 주의사항"
author: "Anselm Jeong"
date: "2026-01-26"
bibliography: "Metaplasticity.bib"
---

메타가소성 모델의 한계와 주의사항

이 가설의 타당성을 비판적으로 검토하는 것이 반드시 필요하다. 이 가설은 기존 학계에서 많은 사람들이 받아들이고 있는 몇 가지 핵심 전제들에 의존하고 있으나, 이들 전제 자체가 충분한 실험적 근거를 결여하고 있다는 점을 간과할 수 없다.

우선, 사이키델릭과는 달리 인간에서 ECT 후에 "가소성 창"이 열린다는 직접적인 증거가 희박하다. 대부분의 신경영상 연구는 ECT 전과 완료 후에 뇌 영상을 얻어 비교한다. 하지만 ECT 직후의 역동적 연결성 변화를 포착하거나 그러한 변화가 시간이 지남에 따라 어떻게 원래대로 돌아오는 지를 추적한 종적 연구는 거의 없다. 우리는 사이키델릭 연구에서 얻어진 통찰을 ECT에 적용한 것이지, 확고한 실험적 데이터를 기반으로 가설을 세운 것이 아니다. 설령 가소성이 창이 열린다 하더라도, 이를 어떻게 확인할 것인지도 막연하며, 그 시점과 지속 기간을 아는 것은 더더욱 어렵다. 예를 들어, 한 연구는 ECT 후에 left angular gyrus의 기능적 연결성이 유의하게 증가하였다가 1개월후에는 원래대로 회복되었다고 보고했다 ([10.3389/fnins.2018.00661](https://doi.org/10.3389/fnins.2018.00661)). 이는 가소성 창의 존재를 시사하는 몇 안되는 연구 중 하나이다. 하지만 ECT 후 매우 촘촘한 간격으로 연속해서 영상을 얻지 않는 이상 결정적 시기를 알기는 무척 어려울 것이다.

또 다른 과제는 대부분의 연구가 시냅스 변화나 기능적 연결성 혹은 BDNF의 농도 변화를 본 연구들로, 신경가소성을 보았던 것이지 "메타가소성"을 측정한 것은 아니다. 이는 특정 시냅스의 변화 정도가 아니라, 시냅스가 외부 자극에 대해 얼마나 변화할 수 있느냐는 능력이다. 동물에서는 뇌 조직에 실험적 개입을 가한 후 장기 강화(LTP) 정도를 포착하여 측정해 볼 수 있겠지만, 살아있는 인간 뇌에서는 그런 실험을 수행할 수 없을 것이다.

유사한 맥락에서 많은 연구들은 말초 BDNF를 뇌 가소성의 대리 표지자로 사용하고 있다. 그러나 이는 심각한 방법론적 문제를 안고 있다 ([10.1016/j.psychres.2024.115946](https://doi.org/10.1016/j.psychres.2024.115946)). 애초에 말초 BDNF가 중추신경계 내의 BDNF 농도를 얼마나 반영할 수 있는지 의문시된다. 일례로 혈장에서 추출했는지 혈청에서 추출했는지에 따라, 약물 투여 후 BDNF 변화 여부에 대한 실험결과가 달라진다. 문제는 혈소판 내에 높은 농도로 존재하는 BDNF가 혈청 분리 과정에서 방출된다는 것이다. 따라서 약물 치료 후에 뇌 내 BDNF가 정말로 상승했는지, 단지 혈소판에서 BDNF의 분리가 더 쉬워졌는지 구분하기 어렵다. 더 심각한 문제는 말초 BDNF 변화와 임상 증상 개선 간의 상관관계가 보이지 않는다는 것이다. 정말로 치료반응이 신경가소성의 증진에 달려있다면 말초 BDNF 상승과 PANSS(양성 및 음성 증상 척도) 또는 HAM-D(해밀턴 우울증 척도) 점수 변화 간에 상관관계가 보여져야 하는데, 이런 관계가 발견되지 않았다.

약물이든 ECT 든 치료와 관계없는 약물의 특성이 BDNF를 변화시켰을 가능성도 있다. 정말로 임상적 호전이 신경가소성 변화에 뒤따르는 것이라면 약물 종류에 상관없이 유의한 변화가 관찰되어야 할 것이다. 그러나 항우울제 중에서는 sertraline만이 유의한 증가를 보였고, 항정신병 약물 중에서도 olanzapine과 risperidone이 메타 분석 결과를 주도했다. ECT에서도 역시 필수적으로 사용되는 마취제가 BDNF 측정 결과를 왜곡할 수 있다. 예를 들어 케타민은 그 자체로도 BDNF 증가를 유발하기 때문에, 마취 보조제로 케타민을 사용했느냐 아니냐에 따라 결과가 달라질 수 있다. 또한 ECT 치료를 받은 환자들이 대부분 항우울제 혹은 항정신병 약물을 복용하고 있었기 때문에, BDNF 증가가 발견되더라도 어떤 것이 원인인지 구분하기 어렵다.

일반적으로 연구자들은 가소성이 증가하는 것을 유연성이 증가하는 것이고 치료의 물고가 트이는 것으로 이해한다. 건강한 뇌는 높은 동적 유연성을 가지기 때문에, 상황과 인지 요구에 따라 다양한 뇌 상태로 자유롭게 전환된다. 그에 비해 우울증 환자의 뇌는 병적 끌개(반추, 자기 비하 등)에 고착되어 상태 전환이 어려워진 것으로 이해되곤 한다. 메타가소성 가설 역시 이러한 전제에 기대고 있다. 그러나 Liu 등(10.21037/apm-21-2723)은 ECT 후 뇌 네트워크가 오히려 더 규칙적이 되고 전체적인 유연성이 오히려 감소한다고 보고하였다.

Sun 등([10.3389/fnhum.2022.852657](https://doi.org/10.3389/fnhum.2022.852657))은 ECT 후에 기능적 연결성이 일부 영역에서 감소한 것을 발견하였다. 저자들은 이를 우울증 환자의 뇌가 치료 전에는 무작위적 네트워크에 가까웠다가, ECT 후에 최적화된 위상 구조를 갖게 된다고 해석하였다. Liu와 Sun 같은 연구자들은 우울증 환자의 뇌는 기능적 연결이 무질서하고 효율성이 떨어지며, ECT는 무질서한 연결을 끊어내고 강력한 동기화를 유도하여 시스템을 초기화하고 안정화시키는 역할을 한다고 생각한다. 뇌 엔트로피(Brain Entropy, BEN)와 관련된 연구도 이를 뒷받침한다. ECT를 받은 우울증 환자의 우측 쐐기앞소엽(precuneus)과 각회(angular gyrus) 등 DMN의 핵심 노드에서 BEN 수치가 유의미하게 감소하였다 ([10.1016/j.pscychresns.2024.111788](https://doi.org/10.1016/j.pscychresns.2024.111788)). 저자들은 높은 BEN을 **뇌 활동의 불규칙성/복잡성 증가로 보았으며, ECT로 DMN의 핵심 노드에서의 BEN이 감소한 것은 DMN이 훨씬 안정적이 되었음을 의미한다고 보았다.**

메타가소성 가설에서 우리는 ECT 직후의 메타가소성 증가와 사이키델릭에 의한 결정적 시기의 재개방을 연결시켰으나, 사실 사이키델릭은 BEN을 오히려 증가시켜 고착된 사고를 해체하는 방식으로 작동한다. 적어도 엔트로피라는 면에서는 ECT와 사이키델릭이 반대방향인 셈이다. 이에 대해 어떻게 해석하느냐는 연구자마다 다를 수 있다. 앞서의 연구자들은 ECT가 혼돈(chaos)을 불러오는 것이 아니라 질서(order)를 회복시키는 방식으로 작동한다고 보고 있으나, 메타가소성 가설에서는 차후에 약물/정신 치료에게 길을 터주기 위해 일시적 혼돈을 주입한다. ECT 직후 환자들이 겪는 인지적 혼란이나 기억력 저하도 정반대의 관점에서 해석될 수 있다. 일시적으로 끌개들을 가로막던 벽이 무너지면서 - 즉 혼돈에 의해 - 혼란과 인지 저하가 수반된다고도 볼 수 있지만, 병적으로 불안정한 네트워크에 강제적으로 질서를 부여하는 과정에서 정상적인 인지 처리에 필요한 미세한 유연성까지 억제되어 일시적 혼란이 초래될 수 있다고 해석할 수도 있다.

다양한 동적 기능적 연결성 지표들을 해석하는 것도 표준화되어 있지 않다. 변이계수(FC Variability), 체류 시간(Dwell Time), 상태 변환 빈도 (Transition Frequency), 네트워크 유연성(network flexiibility), 모듈 변이(module variability) 같은 지표들은 “뇌가 기능적으로 얼마나 유연하게 재구성될 수 있는가”를 반영한다는 점에서 메타가소성과 연결지어볼 수도 있겠지만, 실상 순간순간 바뀌는 기능적 연결성과 신경망의 구조가 바뀌는 메타가소성을 직접 연결짓기엔 무리가 있다. 그러다보니 가설이나 고찰이 엄격한 논리에 의해 구축되기 보다는 비유나 analogy에 의해 형성될 위험이 있다.